100-hours-a-week/2-hertz-be

- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/UserController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/dto/OauthTokenInfo.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/dto/request/UserInfoRequestDto.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/dto/request/UserInterestsRequestDto.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/dto/response/UserInfoResponseDto.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/dto/response/UserInterestsResponseDto.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/entity/User.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/entity/UserOauth.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/entity/enums/AgeGroup.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/entity/enums/Gender.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/entity/enums/Status.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/exception/UserException.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/repository/UserRepository.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/service/InterestsService.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/service/UserService.java
#5 
- User 도메인 추가
- 개인정보 등록 API 추가
- 현재 개발 중단된 상태로 PR 올리며, 추후 수정 예정으로 논의되었습니다
> [#5] Feat: User 도메인 추가 및 개인정보 등록 API

- hertz-be/build.gradle
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/UserController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/entity/enums/Status.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/exception/UserException.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/repository/UserRepository.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/service/UserService.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/exception/GlobalExceptionHandler.java
- hertz-be/src/main/resources/application.properties
#8 
- 랜덤 닉네임 반환 API 작성
- 추후 Redis 재확인 필요
- 
- 기존에 사용하려던 외부 API가 node.js 기반이라 불필요한 작업 리소스 낭비가 생길 것 같아 변경하였습니다.
- [최종 선택한 외부 API](https://nickname.hwanmoo.kr/)
> [#8] Feat: 랜덤 닉네임 반환 API

- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/UserController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/service/UserService.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/auth/filter/JwtAuthenticationFilter.java
- #20
- API 내 accessToken 관련 로직 수정  
- 개인정보 등록 API에서 accessToken 을 Header에서 받아오는 줄 알고 개발을 진행했었습니다..
- 기존대로 롤백했고 정상 작동 확인했습니다
- 
-
> [#20] Fix: accessToken 발급 로직 수정

- hertz-be/src/main/resources/application.properties
- #37 
-  IP 주소를 환경변수에 추가
-  ENV 파일 수정
- AI 서버 API 연동 작업 시작하기전에 pull 받아주세요.
- 없음
> [#37] Feat: AI 서버와 API 연동을 위해 AI 서버 IP 주소를 환경변수에 추가

- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/SignalMessageRepository.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java
- hertz-be/src/main/resources/application.properties
- 없음
- Entity 필드명 수정으로 인해 버그 발생
- "채널방 새 메세지 여부 체크 API" 의 비즈니스 로직에서 필드명 수정
> Fix: "채널방 새 메세지 여부 체크 API" 버그 수정

- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/dto/request/UserInfoRequestDto.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/repository/UserOauthRepository.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/service/UserService.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/common/ResponseCode.java
- 
- 예외 코드 추가하며 ResponseCode 파일이 누락되어 추가하였습니다.
- 
- 
-
> Fix: 개인정보 등록 재시도 시 예외 처리 내 ResponseCode 추가

- hertz-be/src/main/java/com/hertz/hertz_be/domain/interests/service/InterestsService.java
- 
- 취향등록 AI 연동 관련 부분 미완성된 상태로 배포되어 오류가 발생함
- 해당 부분 임시 주석 처리
- 취향등록 내 예외처리 추가
- 
- 
-
> Fix: 취향등록 내 AI 연동 오류 관련 처리

- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java
- #31 
- "튜닝 상대방 추천 API" 로직에서 추천해줄 상대방이 없을 때 예외 처리 추가
- 특정 도메인을 가진 사용자가 한명뿐일 때, AI 추천 알고리즘에서 추천해줄 사람이 없으면 발생하는 예외 처리
> [#37] Fix: "튜닝 상대방 추천 API" 로직에서 추천해줄 상대방이 없을 때 예외 처리 추가

- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/controller/ChannelController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/ChannelRoomRepository.java
- #53 
- relationType 에 잘못된 데이터가 들어가는 오류 수정
-
> [#53] Fix: 채널 보관함 목록 내 카테고리 데이터 오류 수정

- hertz-be/src/main/java/com/hertz/hertz_be/global/auth/token/JwtTokenProvider.java
> chore: accessToken 만료일 원복

- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/ChannelListResponseDto.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/ChannelRoomResponseDto.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/ChannelSummaryDto.java
-
- isLast, isRead 와 같은 boolean 변수들이 JPA 내에서 명시적으로 지정되지 않은 부분을 수정
- 
- 
-
> Refactor: 채널방 관련 DTO 리팩터링

- hertz-be/src/main/java/com/hertz/hertz_be/global/auth/token/JwtTokenProvider.java
- #64 
- accessToken을 원복시켜야 하는데 refreshToken을 잘못 수정하여 두 부분 다 원복하였습니다..
- 
- @stupidyoh 코멘트 달아주신 부분 수정했습니다! 
-
> [#64] Fix: Token 만료일 오기입 수정

- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/AuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/OAuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/UserController.java
- hertz-be/src/main/resources/application.properties
> Refactor: 환경 별 SameSite 설정 분기처리 (2)

- hertz-be/src/main/java/com/hertz/hertz_be/global/auth/token/JwtTokenProvider.java
- 
- accessToken 테스트를 위한 만료 기간 임시단축 (1분)
- 
-
> Chore: accessToken 테스트용 만료 기간 임시 단축

- hertz-be/src/main/java/com/hertz/hertz_be/global/config/SecurityConfig.java
> [#76] Fix: CORS 관련 오류 수정

- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/AuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/OAuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/UserController.java
- #78 
- refreshToken 관련 cookie 설정 변경
- 
> [#78] Fix: refreshToken 관련 오류 수정

- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/AuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/OAuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/UserController.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/config/SecurityConfig.java
- #94 
- CORS 문제 방지 위해 도메인 추가
- RT 토큰을 받을 수 있는 도메인을 지정
- [ㅌ] 기존 기능에 영향을 주지 않는지 확인했습니다.
> [#94] Feat: FE Dev 배포 도메인 등록

- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/AuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/OAuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/UserController.java
> [#94] Feat: 도메인 구체화

- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/AuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/OAuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/UserController.java
> fix: if 조건문 수정

- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/AuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/OAuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/UserController.java
> [#94] Feat: FE 환경에 따라 분기

- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/AuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/OAuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/UserController.java
> feat: FE 도메인 환경변수 밖으로 이동

- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/AuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/OAuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/UserController.java
> [#94] Feat: FE 도메인 구체화

- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/AuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/OAuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/UserController.java
> [#94] Feat: FE 도메인 환경변수 제외시키기

- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/AuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/OAuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/UserController.java
> Feat: 환경변수 삭제

- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/AuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/OAuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/UserController.java
> [#94] Feat: 빌드형태 수정

- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/AuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/OAuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/UserController.java
> [#94] Feat: 서브도메인으로 수정

- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/AuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/OAuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/UserController.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/config/SecurityConfig.java
> [#94] Feat: httpOnly 쿠키 빌드 방식 수정

- hertz-be/src/main/java/com/hertz/hertz_be/global/auth/token/JwtTokenProvider.java
- 
- accessToken 1분 -> 60분 연장
- 
-
> Chore: accessToken 만료 기간 변경

- hertz-be/src/main/resources/application-dev.properties
> feat: AT 유효 시간 2분으로 수정 (RTR 테스트)

- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/service/UserService.java
- hertz-be/src/main/resources/application-dev.properties
> Fix: 개인정보 입력 로직에서 잘못된 RT 저장하는 버그 수정

- hertz-be/src/main/resources/application-dev.properties
- hertz-be/src/main/resources/application-prod.properties
> feat: AT 유효 시간 돌려놓기

- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/AuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/OAuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/UserController.java
- 
- ResponseCookie 내 samesite 관련 설정 추가
- 
> Fix: SameSite 설정 추가

- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/OAuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/exception/ChannelExceptionHandler.java
> Fix: InterestsNotSelectedException 관련 에러처리 임시 200번 response

- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/OAuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/exception/ChannelExceptionHandler.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/interests/service/InterestsService.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/common/ResponseCode.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/exception/AiServerBadRequestException.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/exception/AiServerErrorException.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/exception/AiServerNotFoundException.java
- 
- 튜닝된 상대 반환 API 관련 예외처리 세분화 진행
- 튜닝된 상대 반환 API 내에서 AI와 연동되는 API가 존재하는데, 이에 대한 예외 처리 값을 세분화하여 클라이언트에게 보다 정확한 정보를 제공함
- `AiServerErrorException`의 경우 `code`값을 받아 같은 500에러를 반환하되, 내부 코드값을 달리하여 프론트의 처리를 용이하게 함
- 
-
> Refactor: 튜닝된 상대 반환 API AI 연동 관련 예외처리 세분화 작업 진행

- .github/workflows/cicd-backend.yml
- .github/workflows/discord-pr-merged-notify.yml
- x
- Actions 스크립트 추가(도커알림, CICD)
- 디스코드 PR 알림 스크립트가 없어져서 새로 추가
- CICD 스크립트 추가(현재 CD~Rollback 기능까지 구현)
- Actions 테스트 용으로 PR 머지합니다
> feat: Actions 스크립트 추가(디스코드 PR 알림, CICD)

- .github/workflows/cicd-backend.yml
- x
- 수동 트리거 분기에서 조건문 오타 수정
- 수동 트리거 분기에서 조건문 오타 수정
- 테스트를 위해 PR을 바로 병합합니다.
> fix: 수동 트리거 분기에서 조건문 오타 수정

- .github/workflows/cicd-backend.yml
- x
- 로컬환경 테스트 코드 주석처리
- 로컬환경 테스트 코드 주석처리
- 테스트를 위해 바로 PR 병합을 합니다
> chore: 로컬환경 테스트 코드 주석처리

- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/AuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/OAuthController.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/UserController.java
> Hotfix: token 관련 error 수정

- hertz-be/build.gradle
- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/SignalRoom.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/SignalMessageRepository.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/tuningreport/entity/TuningReport.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/tuningreport/repository/TuningReportRepository.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/repository/UserRepository.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/batch/TuningReportBatchConfig.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/batch/TuningReportJobLauncher.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/batch/TuningReportProcessor.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/batch/TuningReportReader.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/batch/TuningReportScheduler.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/batch/TuningReportWriter.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/config/RestTemplateConfig.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/infra/ai/client/TuningAiClient.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/infra/ai/dto/AiTuningReportGenerationRequest.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/infra/ai/support/UserDataAssembler.java
- hertz-be/src/main/resources/application-dev.properties
- hertz-be/src/main/resources/application-local.properties
- hertz-be/src/main/resources/application-prod.properties
- hertz-be/src/main/resources/application.properties
- hertz-be/src/test/java/com/hertz/hertz_be/global/batch/ProfileCheckTest.java
- hertz-be/src/test/java/com/hertz/hertz_be/global/batch/TuningReportBatchTest.java
- #238 
- Spring Batch 환경 설정 
- Job, Step, Reader, Processor, Writer 추가
- chunk(20) 설정
- Spring Batch 전용 메타 테이블 추가
- 튜닝 리포트 생성 관련 작업
- GPU 서버 연동
- AI 요청용 배치
구성 요소 | 이름 | 설명
-- | -- | --
Job | TuningReportGenerationJob | AI 리포트 생성을 위한 Job
Step | generateReportStep | 매칭 쌍 조회 → AI 호출 → 결과 저장
Reader | JdbcPagingItemReader<SignalRoom> | MATCHED 상태 SignalRoom 조회
Processor | ItemProcessor<SignalRoom, TuningReport> | AI 서버 호출 → 응답 파싱
Writer | JpaItemWriter<TuningReport> | DB에 튜닝 리포트 저장 (is_visible = false)
- 파일별 역할
파일명 | 역할
-- | --
TuningReportBatchConfig.java | Job, Step, Chunk, Reader/Writer 등록
TuningReportReader.java | Reader 설정 분리 (AI 요청 배치용 / 공개 배치용 각각)
TuningReportProcessor.java | AI 호출 로직 (AI 요청 배치용)
TuningReportWriter.java | 결과 저장 또는 공개 처리 + 알림 (Writer 분리 가능)
TuningReportJobLauncher.java …
> [#238] Feat: Spring Batch 작업 및 튜닝 리포트 생성

- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/SignalRoom.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/Tuning.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/enums/Category.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/TuningRepository.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java
- Category enums 관련 파일명 Rename
> Chore: Category enum 수정

- hertz-be/src/test/java/com/hertz/hertz_be/global/batch/ProfileCheckTest.java
- hertz-be/src/test/java/com/hertz/hertz_be/global/batch/TuningReportBatchTest.java
> Chore: 튜닝 리포트 생성 테스트 코드 임시 주석처리

- hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/UserController.java
- null 반환 전에 문자열 먼저 비교하여 NPE 방지
> Fix: UserProfileDTO 관련 NPE 오류 수정

- .github/workflows/docker-cicd-backend.yml
- https://github.com/100-hours-a-week/2-hertz-be/issues/273)
- 도커 CI/CD 적용
- CI 테스트 코드 적용 
- 도커 CI/CD 적용
- CI 테스트 코드 적용 
-
> refactor: 도커 CI/CD 적용

- .github/workflows/docker-cicd-backend.yml
- (https://github.com/100-hours-a-week/2-hertz-be/issues/287)
- 수동 배포로 백엔드 리디렉션 수정 가능 가능하도록 하는 기능 추가
- 도커 환경에서 환경변수 변경에 대한 트리거가 존재 하지 않음
> refactor: 수동 배포로 리디렉션 url 가변적으로 변경 가능 하도록 수정

- .github/workflows/docker-cicd-backend.yml
- Merge 시 Stage 환경에 맞춰 분기하도록 변경
- Merge 시 Stage 환경에 맞춰 분기하도록 변경
> hotfix: Merge 시 Stage 환경에 맞춰 분기하도록 변경

- .github/workflows/docker-cicd-backend.yml
- hotfix: 수동 배포 시 branch 정보가 들어가지 않는 문제 해결
> hotfix: 수동 배포 시 branch 정보가 들어가지 않는 문제 해결

- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/config/SocketIoConfig.java
- 웹소켓 커넥션 오류로 인한 임시 중단 hotfix 적용
- 추후 커넥션 오류 해결 후 주석 해제 예정
> Hotfix: socket.io 실행 임시 중단

- .github/workflows/cicd-backend.yml
- .github/workflows/docker-cicd-backend.yml
- 기존 PROD 환경이 사용 중지되면서 트리거되지 않게 변경
- Discord 메세지 변경
- 기존 PROD 환경이 사용 중지되면서 트리거되지 않게 변경
- Discord 메세지 변경
> refactor: 기존 PROD 환경이 사용 중지되면서 트리거되지 않게 변경&style: Discord 메세지 변경

- .github/workflows/cicd-backend.yml
> fix: 테스트 코드 제거

- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/SignalMessageRepository.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/socketio/SocketIoController.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/socketio/SocketIoServerRunner.java
- hertz-be/src/main/resources/application-dev.properties
- #331  
- #332  
- socket.io 서버 시작 시 포트 충돌 방지용 try-catch 추가
> Fix: socket.io 오류 해결

- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/request/v2/SignalMatchingRequestDto.java
- Long 타입의 경우 NotBlank 어노테이션을 허용하지 않아 NotNull로 수정
- Long 타입은 개념상 공백이 없기 때문에 NotBlank가 아닌 NotNull 어노테이션을 사용해야 함
> Refactor: Long 타입 어노테이션 수정

- hertz-be/src/main/java/com/hertz/hertz_be/global/socketio/SocketIoServerRunner.java
- #341 
- socket.io 서버 구동 및 종료 리팩터링
> [#341] Refactor: socket.io 서버 구동 및 종료 리팩터링

- hertz-be/src/main/java/com/hertz/hertz_be/global/socketio/SocketIoService.java
> Hotfix: socket.io 실시간 채팅 내 SSE 연동

- hertz-be/.gitignore
- hertz-be/build.gradle
- hertz-be/src/main/java/com/hertz/hertz_be/global/socketio/SocketIoController.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/socketio/SocketIoServerRunner.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/socketio/SocketIoService.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/socketio/SocketIoSessionManager.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/webpush/FCMInitializer.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/webpush/controller/FCMController.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/webpush/dto/FCMTokenRequestDTO.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/webpush/service/FCMService.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/webpush/token/FCMTokenDao.java
- hertz-be/src/main/resources/application.properties
- #359 
- FCM WebPush 토큰 발급 및 저장 로직 추가
- Socket IO 관련 코드 리팩토링
- 클라이언트에서 FCM을 통해 브라우저 푸시 권한 요청 및 토큰 발급 완료
- 해당 토큰을 백엔드로 전달하여 UserID 기준으로 Redis에 저장하는 로직 구현 완료
- socket.io 서버 재기동 시 포트충돌로 인해 정상적으로 구동되지 않는 부분 수정
- socket.io sessionManager로 현재 접속자 관리 로직 추가
> [#359] Feat: FCM WebPush 토큰 발급 및 저장 로직 추가

- hertz-be/src/main/java/com/hertz/hertz_be/global/socketio/SocketIoService.java
> Hotfix: socket.io SSE 관련 오류 hotfix

- hertz-be/src/main/java/com/hertz/hertz_be/global/socketio/SocketIoService.java
- socket.io Serivce 내 sse 알림 로직 추가 (주석 해제)
> Hotfix: socket.io sse 관련 오류 재적용 (주석 해제)

- hertz-be/src/main/java/com/hertz/hertz_be/global/webpush/controller/FCMController.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/webpush/dto/FCMTokenResponseDTO.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/webpush/responsecode/FCMEventType.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/webpush/service/FCMService.java
- WebPush token 관련 response 누락된 내용 추가
> Refactor: Webpush response 누락 내용 추가

- hertz-be/src/main/java/com/hertz/hertz_be/global/webpush/controller/FCMController.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/webpush/dto/FCMTokenResponseDTO.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/webpush/responsecode/FCMEventType.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/webpush/responsecode/FCMResponseCode.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/webpush/service/FCMService.java
> Refactor: Webpush response 누락 내용 추가 (responseCode 추가)

- hertz-be/src/main/java/com/hertz/hertz_be/global/socketio/SocketIoController.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/socketio/SocketIoService.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/socketio/SocketIoSessionManager.java
- Branch 충돌로 인한 소스 누락 오류 조치
- 이전에 반영했던 항목들이 다시 롤백되어 있어 정상적으로 적용되어 있지 않았음
> Fix: Branch 충돌 관련 소스 누락 오류 조치

- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/SignalRoomRepository.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/v1/ChannelService.java
- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/v3/ChannelService.java
- #395 
- 채널 도메인의 채팅 목록 조회 API 비즈니스 로직 리팩토링
- 정렬 기준을 `SignalRoom.createdAt` → `마지막 메시지 시간(SignalMessage.sendAt)` 기준으로 변경
- `ChannelRoomProjection` 제거 및 `SignalRoom` 엔티티 기반의 객체 탐색 방식으로 전환
- 기존에는 채팅 목록 조회 시 projection 기반 native 쿼리를 사용해 모든 데이터를 한 번에 조회했으나, 도메인 응집도가 떨어지고 유지보수가 어려웠음
- 사용자의 UX 측면에서 **실제 마지막 메시지를 기준으로 채팅방이 정렬되어야** 하므로 쿼리 로직을 수정함
- 새로운 정렬 기준에 맞게 `SignalRoomRepository.findAllOrderByLastMessageTimeDesc(...)` native 쿼리를 정의
- 내부적으로 `signal_message` 테이블을 서브쿼리로 묶어 각 채팅방의 `MAX(send_at)`을 계산
- 서비스단에서는 `ChannelRoomProjection` 제거 후, `SignalRoom`을 순회하며:
- `.getPartnerUser()`로 상대방 정보 추출
- `.getMessages()`로 마지막 메시지 추출 및 복호화
- 나간 방은 `.isUserExited()`로 필터링
- 반환 DTO는 기존 `v1.ChannelSummaryDto` 포맷을 유지하여 클라이언트 변경 없이 통합됨
- 없음
- 없음
> [#395] Refactor: 채팅 목록 조회 API의 정렬 기준을 마지막 메시지 시간 기준으로 수정 및 객체지향 방식 리팩토링

- hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/AsyncChannelService.java
- hertz-be/src/main/java/com/hertz/hertz_be/global/webpush/service/FCMService.java
- #385 
- 상대방 매칭 결정 시 WebPush 알림 추가
- 상대방 매칭 결정에 대한 알림을 외부에서도 받을 수 있도록 하여 서비스 사용을 유도함
> [#385] Feat: WebPush 상대방 매칭 결정 알림 기능 구현
