100-hours-a-week/2-hertz-be

hertz-be/src/main/java/com/hertz/hertz_be/auth/controller/AuthController.java, hertz-be/src/main/java/com/hertz/hertz_be/auth/dto/response/ReissueAccessTokenResponseDTO.java, hertz-be/src/main/java/com/hertz/hertz_be/auth/exception/RefreshTokenExceptionHandler.java, hertz-be/src/main/java/com/hertz/hertz_be/auth/exception/RefreshTokenInvalidException.java, hertz-be/src/main/java/com/hertz/hertz_be/auth/service/AuthTokenService.java, hertz-be/src/main/java/com/hertz/hertz_be/auth/service/RefreshTokenService.java, hertz-be/src/main/java/com/hertz/hertz_be/global/TestLoginController.java, hertz-be/src/main/java/com/hertz/hertz_be/global/TestLoginRequestDTO.java, hertz-be/src/main/java/com/hertz/hertz_be/global/auth/handler/CustomAuthenticationEntryPoint.java, hertz-be/src/main/java/com/hertz/hertz_be/global/auth/token/JwtTokenProvider.java, hertz-be/src/main/java/com/hertz/hertz_be/global/common/ResponseCode.java, hertz-be/src/main/java/com/hertz/hertz_be/global/common/ResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/global/config/SecurityConfig.java, hertz-be/src/main/java/com/hertz/hertz_be/global/exception/GlobalExceptionHandler.java, hertz-be/src/main/resources/application.properties
- #3 
- Auth 도메인 추가
- 공통 예외 처리를 위한 클래스 추가
- 공통 상수 관리를 위한 클래스 추가
- 공통 ResponseDTO와 ResponseCode 클래스 추가
- Redis 관련 설정과 환경변수 추가
- RT에 Secure와 SameSite 설정
- 유효기간이 지난 AT를 재발급 받기 위한 API 구현 (RT도 같이 유효기간 리셋)
- user라는 도메인 안에서 AT, RT, 소셜 로그인 관련 로딕을 관리하게되면   
user 도메인이 너무 많은 책임을 맡을 것 같아, Auth 관련 로직을 위한 domain 추가
=> [#3] Feat: Refresh Token 기반 Access Token 재발급 API 구현

hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/OAuthController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/repository/OAuthRedisRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/global/config/SecurityConfig.java
#12 
- cors() 설정을 HttpSecurity에 추가
- 카카오 소셜 로그인 APIㄹ 주소 오타 수정
- cors() 설정을 일단 모든 엔드포인트 허용 (개발단계용)
=> [#9] Feat: kakao oauth 테스트를 위해 cors 설정을 HttpSecurity에 추가

hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/controller/ChannelController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/request/SendSignalRequestDTO.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/SendSignalResponseDTO.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/SignalMessage.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/SignalRoom.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/enums/Category.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/enums/MatchingStatus.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/exception/AlreadyInConversationException.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/exception/BaseChannelException.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/exception/ChannelExceptionHandler.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/exception/UserWithdrawnException.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/SignalMessageRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/SignalRoomRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/UserController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/dto/request/UserInfoRequestDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/entity/User.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/entity/enums/AgeGroup.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/entity/enums/Gender.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/entity/enums/MembershipType.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/service/UserService.java, hertz-be/src/main/java/com/hertz/hertz_be/global/common/ResponseCode.java, hertz-be/src/main/java/com/hertz/hertz_be/global/exception/GlobalExceptionHandler.java
- #14 
- 첫 메세지 전송 시 채팅방 생성 또는 기존 채팅방 ID 반환 기능 추가  
- 추천 사용자 중 마음에 드는 사용자에게 요청/승인 과정 없이 바로 첫 메세지를 전송할 수 있도록 기능 구현  
- 상대방과의 채팅방이 존재하지 않을 경우, 새로운 채팅방을 생성하고 첫 메세지를 포함시켜 저장  
- 이미 채팅방이 존재할 경우, 해당 채팅방 ID를 반환하여 중복 생성을 방지  
- 사용자 간 매칭 상태나 별도의 승인 절차 없이 즉시 대화 시작 가능  
- 주요 예외 상황 및 응답 처리:
1. ✅ **성공적인 요청 시**
2. 🔁 **이미 대화 중인 사용자일 경우**
3. ❌ **상대방이 탈퇴한 사용자일 경우**
=> [#14] Feat: 추천 사용자 대상 첫 메세지 전송 API 구현 및 채팅방 생성 처리 

hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/UserController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/dto/request/UserInfoRequestDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/dto/response/UserInfoResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/entity/User.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/entity/UserOauth.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/service/UserService.java, hertz-be/src/main/java/com/hertz/hertz_be/global/auth/filter/JwtAuthenticationFilter.java, hertz-be/src/main/java/com/hertz/hertz_be/global/common/ResponseCode.java
- #5 
- API 내 Redis/refreshToken 로직 추가
- accessToken은 body로 반환, refreshToken은 Cookie로 반환하도록 수정
- User entity 및 DTO 관련 오류로 인한 타입 수정
- API 내에서 Redis 내의 refreshToken을 받아오는 로직을 추가했습니다.
- header를 통해 받아온 accessToken을 다시 body로 넣어주는 작업을 추가했습니다.
- cookie내 refreshToken 만료 기간 설정 시 계산하는 과정을 추가했습니다.
- 이상한 부분 있으면 말씀 부탁드려요!
-
=> [#5] Feat: 개인정보 등록 API 마무리

hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/SignalMessage.java, hertz-be/src/main/java/com/hertz/hertz_be/global/auth/token/JwtTokenProvider.java, hertz-be/src/main/resources/application.properties
- #22 
- JWT 비밀키를 코드 내 고정 생성 방식에서 외부 설정 방식으로 변경
- application.properties 또는 환경변수에서 비밀키 주입받도록 구현
- 기존에는 `JwtTokenProvider`에서 서버 실행 시마다 새로운 비밀키를 생성하고 있었습니다.
```java
this.key = Keys.secretKeyFor(SignatureAlgorithm.HS256);
- 이로 인해 서버 재시작 시 이전에 발급된 토큰이 모두 무효화되는 문제가 있었습니다.
- 이를 해결하기 위해 @Value("${jwt.secret}")를 통해 Base64 인코딩된 비밀키를 외부에서 주입받도록 수정하였고,
@PostConstruct에서 디코딩 후 Key 객체로 변환하는 로직을 추가했습니다.
- 비밀키는 application.properties, application.yml, 또는 .env 파일에서 관리할 수 있으며,
운영 환경에서는 환경변수 JWT_SECRET으로 설정하면 됩니다.
##🆕 ENV 템플릿 업데이트
```
DB_HOST=database_host
DB_PORT=database_port
DB_NAME=your_database_name
DB_USERNAME=your_database_username
DB_PASSWORD=your_database_password
SWAGGER_ENABLED=true
REDIS_HOST=redis_host
REDIS_PORT=redis_port
REDIS_PASSWORD=redis_password
KAKAO_CLIENT_ID=kakao_key …
=> [#22] Feat: JWT 비밀키 환경 변수 설정으로 외부화

hertz-be/build.gradle, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/controller/ChannelController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/TuningResponseDTO.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java, hertz-be/src/main/java/com/hertz/hertz_be/global/auth/filter/JwtAuthenticationFilter.java, hertz-be/src/main/java/com/hertz/hertz_be/global/common/ResponseCode.java, hertz-be/src/main/java/com/hertz/hertz_be/global/config/SecurityConfig.java
- #24 
- GET `/api/v1/tuning` API 엔드포인트 추가
- 임시 더미 데이터를 반환하는 서비스 로직 구현
- `TuningResponseDTO`, `TuningService`, `TuningController` 생성
- 공통 응답 포맷(`ResponseDto`) 기반으로 응답 구성
AI 기반의 튜닝 상대 추천 시스템이 아직 완성되지 않아, 프론트엔드 UI 개발을 위한 더미 데이터 기반 API를 임시로 구현했습니다.  
이번 PR의 목적은 실제 AI 서버 응답을 가정한 JSON 데이터를 반환함으로써 프론트에서 화면 흐름과 컴포넌트 개발을 원활히 진행할 수 있도록 하는 것입니다.
- `@AuthenticationPrincipal Long userId`를 통해 사용자 인증 정보를 받습니다.
- 서비스 계층에서 더미 데이터를 반환하며, 실제 AI 서버 연동 시 해당 로직은 교체될 예정입니다.
- API 응답 구조는 실제 응답 포맷과 최대한 유사하게 구성되어 향후 변경 작업이 최소화되도록 설계했습니다.
1. 요청 성공
=> [#24] Feat: api tuning match dummy

hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/exception/OAuthStateInvalidException.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/exception/ProviderInvalidException.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/exception/RateLimitException.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/exception/RefreshTokenInvalidException.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/controller/ChannelController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/exception/AlreadyInConversationException.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/exception/UserWithdrawnException.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/SignalMessageRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java, hertz-be/src/main/java/com/hertz/hertz_be/global/common/ResponseCode.java, hertz-be/src/main/java/com/hertz/hertz_be/global/exception/GlobalExceptionHandler.java, hertz-be/src/main/java/com/hertz/hertz_be/global/exception/InternalServerErrorException.java
- #26 
- GET /api/v1/new-messages API 구현
- SignalRoom, SignalMessage 관계 기반으로 새 메시지 존재 여부 확인 로직 추가
- 사용자가 참여한 SignalRoom 중, 본인이 보낸 메시지를 제외하고 읽지 않은 메시지가 하나라도 존재하는지 확인하는 API입니다.
- SignalMessage의 senderUserId 필드가 User 타입이므로, existsBy 쿼리 메서드에서 User 엔티티를 직접 비교하도록 구현했습니다.
1. 현재 로그인한 사용자의 `sentSignalRooms`와 `receivedSignalRooms`를 모두 가져와 병합
2. 해당 SignalRoom 리스트에 대해 `isRead = false` && `senderUser != 현재 유저` 조건을 만족하는 메시지 존재 여부 확인
3. 결과에 따라 다음 응답 반환:
- NEW_MESSAGE / NO_ANY_NEW_MESSAGE
1. 새 메세지가 있을 경우
2. 새 메세지가 없을 경우
=> [#26] Feat: 채널방 새 메시지 여부 조회 API 구현

hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/controller/ChannelController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/ChannelListResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/ChannelSummaryDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/ChannelJoin.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/ChannelMessage.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/ChannelMessageLastRead.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/ChannelRoom.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/ChannelRoomRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/projection/ChannelRoomProjection.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java, hertz-be/src/main/java/com/hertz/hertz_be/global/common/ResponseCode.java
- #29
- `ChannelRoomProjection` 인터페이스 기반 Projection 적용  
- `ChannelSummaryDto.fromProjection()` 메서드 구현  
- `User` 엔티티에서 `@Setter` 제거, 대신 연관관계 설정용 메서드(`registerUserOauth`) 추가  
- 개인 채널보관함 목록을 효율적으로 조회하기 위해 **interface 기반 Projection**을 적용했습니다.  
- 엔티티 전체가 아닌 필요한 필드만 조회하도록 하여 성능을 최적화했습니다.  
- `ChannelSummaryDto`에서 `ChannelRoomProjection`을 활용한 `fromProjection()` 메서드를 통해 Projection → DTO 매핑을 처리했습니다.  
- `User` 엔티티의 `userOauth` 필드에 대해 setter를 제거하면서, 연관관계를 안전하게 맺기 위한 `registerUserOauth()` 메서드를 추가했습니다.
- Projection 방식이 적절하게 사용되었는지 확인해주시면 감사하겠습니다.
- `User`와 `UserOauth` 간 연관관계 설정 방식이 객체지향적으로 잘 정리되었는지 검토 부탁드립니다.
-
=> [#29] Feat: 개인 채널보관함 목록 반환 API

.github/workflows/discord-pr-merged-notify.yml
- Discord PR 알림 기능 추가
github actions 스크립트: `discord-pr-merged-notify.yml`
- `develop` 브랜치에 PR 후, Merge 시에만 해당 트리거 동작
=> Feat: Discord PR 알림 기능 추가(Merge 시에 동작)

hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/controller/ChannelController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/request/SignalMessageRequestDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/ChannelRoomResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/SignalMessage.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/SignalRoom.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/exception/ChannelNotFoundException.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/exception/UnauthorizedAccessException.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/SignalMessageRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/SignalRoomRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/entity/User.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/repository/UserRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/global/common/ResponseCode.java
- #30 
- #31 
- 채널방 메세지 전송 API 구현
- 특정 채널방 반환 API 구현
- 사용자가 특정 채널방(`/api/v1/channel-rooms/{channelRoomId}`)을 선택하면 해당 채널방의 메시지 목록을 최신순으로 최대 20개까지 페이징하여 조회할 수 있도록 구현했습니다.  
- 응답에는 상대방의 정보(`partnerId`, `partnerNickname`, `partnerProfileImage`)와 관계 유형(`relationType`: `SIGNAL` 또는 `MATCHING`)이 포함됩니다.  
- 메시지는 `messageSendAt` 기준으로 최신순으로 정렬되어 반환됩니다.  
- 프론트에서 무한 스크롤 형태로 사용할 수 있도록 페이지네이션 정보(`pageNumber`, `pageSize`, `isLast`)를 함께 제공합니다.  
- 상대방이 탈퇴한 경우에는 `410 USER_DEACTIVATED` 응답을 반환하도록 예외처리를 추가했습니다.  
- 
-
=> [#30][#31] Feat: 채널방 메세지 전송 및 특정 채널방 반환 API 구현

hertz-be/src/main/java/com/hertz/hertz_be/domain/user/dto/request/UserInfoRequestDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/service/UserService.java
- .
- FE 측 로그인 테스트를 용이하게 하기 위하여 임시 로직 수정
- 개인정보 등록 API 요청 시 
- `isTest = true` 일 경우 테스트용으로 인지하여 JPA save 하지 않도록 수정
- `isTest = false` 일 경우 기존 로직 + email 관련 비즈니스 로직 내 처리 (`provider_id + @kakaotech.com`)
- 위 내용 관련하여 API 명세서 수정하였습니다.
-
=> Test: FE 측 로그인 테스트가 불편하여 임시 변경

hertz-be/src/main/java/com/hertz/hertz_be/domain/user/dto/request/UserInfoRequestDto.java
- 
- user 관련 DTO에서 email 필드의 `@NotBlank` annotation을 삭제함
- email 입력 여부에 따라 사용자를 다르게 판단하기 때문에 `@NotBlank` 를 할 수 없음
- 
-
=> Fix: email 필드 NotBlank 어노테이션 삭제

hertz-be/src/main/java/com/hertz/hertz_be/domain/user/dto/request/UserInfoRequestDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/repository/UserOauthRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/service/UserService.java
- 
- 같은 사용자 계정으로 개인정보 등록 API 호출이 2회 이상 실행될 경우의 예외 처리 추가
- 
- 개인정보 등록 (최초 요청)
- 개인정보 등록 (2회 이상 요청)
=> Fix: 개인정보 등록 재시도 시 예외 처리

hertz-be/build.gradle, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/controller/ChannelController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/TuningResponseDTO.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/Tuning.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/TuningResult.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/exception/ChannelExceptionHandler.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/exception/InterestsNotSelectedException.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/TuningRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/TuningResultRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/interests/repository/UserInterestsRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/entity/User.java, hertz-be/src/main/java/com/hertz/hertz_be/global/common/ResponseCode.java, hertz-be/src/main/java/com/hertz/hertz_be/global/exception/AiServerErrorException.java, hertz-be/src/main/java/com/hertz/hertz_be/global/exception/GlobalExceptionHandler.java
- #37 
- 기존 더미 데이터를 반환하던 튜닝 API를 AI 서버 연동 방식으로 변경
- 중복 대화 상대 필터링 로직 추가
- AI 서버 호출 및 결과 저장 로직 리팩토링 (메서드 분리)
- 기존에는 AI 서버가 구현되지 않아 `getTunedUser()`에서 더미 데이터를 사용하였습니다.
- 이제 AI 서버가 완성됨에 따라 실제 추천 유저 목록을 받아와 DB에 저장하고, 
이미 대화방이 존재하지 않는 유저를 찾아 반환하는 로직을 구현했습니다.
- `fetchAndSaveTuningResultsFromAiServer()`로 분리하여 중복 제거 및 재사용성을 높였습니다.
- `TuningResult`가 소진되거나 유효하지 않은 경우, 반복적으로 AI 서버를 호출하여 새로 추천을 받습니다.
=> [#37] Feat: AI 서버 연동을 통한 튜닝된 상대 추천 API 구현

hertz-be/src/main/java/com/hertz/hertz_be/global/auth/token/JwtTokenProvider.java
- 
- accessToken 만료 기간 연장
- 테스트 용이성을 위하여 accessToken 만료 기간을 임시로 연장하였습니다. 
- 
-
=> Fix: accessToken 만료일 임시 연장 (테스트)

hertz-be/build.gradle, hertz-be/src/main/java/com/hertz/hertz_be/domain/interests/dto/request/UserAiInterestsRequestDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/interests/dto/response/UserInterestsResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/interests/exception/BaseInterestsException.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/interests/exception/DuplicateIdException.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/interests/exception/InterestsExceptionHandler.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/interests/exception/InvalidException.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/interests/exception/RegisterBadRequestException.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/interests/exception/SimilarityUpdateFailedException.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/interests/service/InterestsService.java, hertz-be/src/main/java/com/hertz/hertz_be/global/common/ResponseCode.java, hertz-be/src/main/java/com/hertz/hertz_be/global/config/WebClientConfig.java
- #41 
- 취향등록 시 사용자 정보를 AI 벡터 DB에 저장할 수 있도록 API 연동
- 사용자의 개인정보, 취향정보(키워드, 관심사)를 AI API를 통해 전달
- 각 예외에 대한 예외처리 추가
- 
-
=> [#41] Feat: 취향 등록 API AI 연동

hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java
- #52 
- 채널방 내에서 메세지의 정렬 순서가 내림차순으로 되어 있는 오류 수정
- 메세지가 내림차순으로 되어있어 순서가 맞지 않음
- 정렬 변경
- 
-
=> [#52] Fix: 특정 채널방 내 메세지 정렬 수정

hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/SignalRoom.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/exception/CannotSendSignalToSelfException.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/exception/ChannelExceptionHandler.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/SignalRoomRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java
- #56 
- `signal_room` 테이블 내 `user_pair_signal` 컬럼 추가
- 사용자의 시그널 상대가 본인일 경우에 대한 예외 처리 추가
1. `signal_room` 테이블 내 `user_pair_signal` 컬럼이 누락되어 있어 추가하였습니다. (양방향 중복 방지용 컬럼)
1. 테이블 정의서 상으로는 `user_pair_signal` 에 STORED GENERATED COLUMN 제약 조건을 부여하려 했으나, JPA 상에서 해당 제약 조건을 직접 매핑하거나 조작할 수 없어 entity 내에 아래와 같이 설정했습니다.
```
@Column(name = "user_pair_signal", nullable = false, unique = true, length = 35)
private String userPairSignal;
```
2. `user_pair_signal` 컬럼 추가로 인해 '시그널 보내기' 쪽 Serivce 로직을 수정했습니다.
1. `ChannelService.java > sendSignal`
```
@Transactional
public SendSignalResponseDTO sendSignal(Long senderUserId, SendSignalRequestDTO dto) {
User sender = userRepository.findById(senderUserId)
.orElseThrow(InternalServerErrorException::new);
User receiver = …
```
=> [#56] Fix: 채널 보관함 목록 관련 컬럼 누락건 수정

hertz-be/src/main/java/com/hertz/hertz_be/domain/interests/exception/InterestsExceptionHandler.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/interests/exception/InvalidInterestsInputException.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/interests/service/InterestsService.java
- #58 
- 누락되어있던 422 예외를 추가하였습니다.
- 키워드 및 취향 정보에 대한 데이터 누락보다 사용자의 DB 저장 여부를 먼저 판단하고 있어 해당 로직을 추가/수정했습니다.
- 이에 대해 관련 예외를 추가하였습니다.
- 
-
=> [#58] Fix: 취향 등록 관련 데이터 누락 시 예외처리

hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/interests/repository/UserInterestsRepository.java
- 없음
- 특정 사용자가 아직 취향을 등록하지 않았는데, 튜닝 상대 API를 요청하면 예외 처리 로직 수정
- 위와 같습니다.
=> Fix: 아직 등록된 취향이 없을 때 예외 처리 수정

hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/AuthController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/OAuthController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/UserController.java, hertz-be/src/main/java/com/hertz/hertz_be/global/config/SecurityConfig.java
- #94 
---
- `refreshToken` 쿠키 설정 로직을 환경 변수 `is.local`에 따라 분기하도록 수정  
- 로컬 환경에서는 `secure`, `domain` 미설정  
- 운영 환경에서는 `.secure(true)`, `.domain(".hertz-tuning.com")` 설정
---
기존에는 쿠키 설정이 운영 도메인에 고정되어 있어, 로컬 환경(`localhost`)에서는 쿠키가 저장되지 않는 문제가 있었습니다.  
이를 해결하기 위해 `is.local` 값을 기준으로 `ResponseCookie` 설정을 조건부로 처리하도록 리팩토링했습니다.
- **로컬 (`is.local=true`)**  
- `secure`, `domain` 생략 → `localhost`에서 쿠키 저장 가능  
- **운영 (`is.local=false`)**  
- `secure=true`, `domain=.hertz-tuning.com` → `dev.hertz-tuning.com`, `hertz-tuning.com`에서 쿠키 공유 가능
📌 적용된 위치:
- `OAuthController`
- `AuthController`
- `UserController`
---
---
- 혹시 더 명확하게 설정 분리할 수 있는 구조가 있다면 피드백 환영입니다.
---
- 없음
=> [#94] Feat: RT를 httpOnly 쿠키에 담을 때 FE 클라이언트 서브 도메인 지정

hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/exception/ChannelExceptionHandler.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/exception/ForbiddenChannelException.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/exception/UserNotFoundException.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/ChannelRoomRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java
- #92 
- 사용자에 따른 `is_read` 값 반환 변경
- 메세지 읽음 처리 update 쿼리 추가
- 시그널 관련 예외처리 추가
- 기존에는 is_read 필드의 값을 그대로 조회하고 있었는데, 같은 채널방에 대해 is_read를 다르게 보여줘야 하기 때문에 CASE 쿼리문 추가
- '특정 채널방 반환 API' 호출 시 해당 채널방의 메세지를 모두 읽음 처리할 수 있도록 update 쿼리 및 비즈니스 로직 수정
- 채널 도메인 내 예외처리 세분화
- 사용자 : `UserNotFoundException`, `UserWithdrawnException`
- 채널 : `ForbiddenChannelException`
- 
-
=> [#92] Fix: 메세지 읽음 처리 관련 오류 수정 및 리팩토링

hertz-be/src/main/java/com/hertz/hertz_be/global/auth/token/JwtTokenProvider.java, hertz-be/src/main/resources/application-dev.properties, hertz-be/src/main/resources/application-local.properties, hertz-be/src/main/resources/application-prod.properties, hertz-be/src/main/resources/application.properties
- #132 
- `application.properties` → 공통 설정으로 유지
- `application-dev.properties`, `application-prod.properties`로 환경별 설정 분리
- `spring.profiles.active` 설정에 따라 실행 환경 분기 적용
- JWT Access Token 유효시간을 properties에서 설정 가능하도록 변경
- dev 환경: 180분 (3시간)
- prod 환경: 30분 (기본값)
---
- `src/main/resources/application.properties`
- `src/main/resources/application-dev.properties`
- `src/main/resources/application-prod.properties`
- src/main/resources/application-local.properties`
---
1. env 파일에서 ACTIVE=(dev,prod,local 중 하나) 추가
=> [#132] Feat: 프로파일 기반 properties 분리 및 JWT AT 유효시간 환경변수화

hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/SignalMessage.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/enums/MatchingStatus.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/ChannelRoomRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/SignalMessageRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/SignalRoomRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/projection/ChannelRoomProjection.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/projection/RoomWithLastSenderProjection.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java
- #92 
- 메세지 읽음 처리 수정
- MatchingStatus ENUM 통일화
- signal_message 테이블 내 인덱스 설정 추가 (읽음 처리 관련)
- 시그널/채널 관련 쿼리 수정 및 이동
1. 메세지 읽음 처리 수정
1. 특정 채널방 반환 API 호출 시 마지막으로 메세지를 보낸 사용자 아이디를 체크하여 currentUser와 다를 경우에만 is_read = true로 update하도록 수정했습니다.
2. signal_message 테이블 내 인덱스 설정 추가 (읽음 처리 관련)
1. 채널보관함 목록 조회 시마다 signal_room_id별 send_at DESC를 자주 조회하기 때문에 인덱스 설정을 추가하였습니다. (JPA)
3. 시그널/채널 관련 쿼리 수정 및 이동
1. 기존 로직에서 시그널과 채널을 혼동하여 Repository를 사용하였습니다. 현재 '채널' 도메인은 사용하지 않기 때문에 채널의 쿼리를 모두 시그널로 옮겼습니다.
2. 시그널 중에서도 Message/Room 으로 나뉘었는데, 비즈니스 로직 상에서 사용되는 쿼리가 어디에 더 적합한지 판단하여 옮기는 작업을 진행하였습니다.
- 
-
=> [#92] Fix: 시그널 메세지 읽음 처리 오류 수정

hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/OAuthController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java
- 소셜 로그인 API 예외 추가 
- 소셜 로그인 시, 이미 회원가입된 사용자이고 취향을 선택하지 않았다면 예외처리
=> Feat: 소셜 API 로그인시, 이미 회원가입된 사용자인데 취향선택하지 않았음 예외 처리 추가

.gitignore, hertz-be/.gitignore
- #84 
- Shenandoah GC 설정 추가로 인해 .gitignore 수정
- 로컬 및 개발/운영 VM Options 설정 필요 (개발/운영의 경우 @DDongu 작업 완료)
- 로컬 IntelliJ 내 Shenandoah GC 관련 VM Options 추가
- `-XX:+UseShenandoahGC -Xms512m -Xmx1024m -Xlog:gc*:file=logs/gc.log:time,uptime,level,tags:filecount=5,filesize=20m`
- 이전 이력 쌓이는 파일 개수 : 5개
- 파일 하나당 최대 용량 20MB
- DEV : -XX:+UseShenandoahGC -Xms1g -Xmx2g
- PROD : -XX:+UseShenandoahGC -Xms2g -Xmx2g
- DEV에서 `-Xms < -Xmx` 로 설정하는 이유
- 메모리 부담을 줄이되 최대 상황도에 대한 대비를 위해
- GC 튜닝이나 메모리 누수 탐지 등과 같은 모니터링에 적절
- PROD 에서 `-Xms = -Xmx` 로 설정하는 이유
- JVM 힙 사이즈가 변하지 않도록 고정하기 위해
- 힙 사이즈가 변하지 않으면 GC가 힙을 확장/축소하지 않기 때문에 GC pause가 더 안정적이고 예측하기 좋음
- CPU spike나 성능 튐 방지
- 
-
=> [#84] Chore: Shenandoah GC 설정 추가

.github/workflows/cicd-backend.yml
- backend cicd 스크립트 중 배포환경 구분이 안되는 오류 해결
- 조건문에서 branch를 바로 읽어오도록 변경
=> fix: backend cicd 스크립트 중 배포환경 구분이 안되는 오류 해결

hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/controller/ChannelController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/request/SignalMatchingRequestDTO.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/SignalRoomRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/interests/service/InterestsService.java, hertz-be/src/main/java/com/hertz/hertz_be/global/common/ResponseCode.java
- #85 
- #86 
- 시그널 보내기 후 매칭 수락/거절 API 추가
- 시그널 전송 후 24시간 동안 대화 가능, 이후에는 매칭 여부에 따라 대화방 유지 여부가 달라짐
- 개인 채널인 경우에만 해당함 (그룹 채널 x)
- 2명 모두 매칭 수락을 해야만 시그널 -> 매칭으로 성사됨
- 1명이라도 매칭 거절을 할 경우 매칭 성사되지 않음
=> Feat: 매칭 수락/거절 API 구현

hertz-be/build.gradle, hertz-be/src/main/java/com/hertz/hertz_be/domain/interests/service/InterestsService.java, hertz-be/src/main/java/com/hertz/hertz_be/global/config/RetryConfig.java
- #195 
- AI SERVER Response `409` - AI SERVER에 이미 등록된 사용자인 경우, 예외처리로 throw 하지 않고 200으로 처리하여 다음 과정으로 넘어갈 수 있도록 함
- AI SERVER Responce `404` - AI SERVER에 등록되지 않은 사용자를 튜닝페이지에서 조회하려 하는 오류, BE DB와 AI DB에 정상적으로 저장되지 않은 상태로 다음 기능으로 넘어감 -> AI SERVER 호출 전에 BE DB에 저장하는 트랜잭션이 커밋된 후 실행되도록 함 (TransactionSynchronizationManager)
- AI SERVER 데이터 저장 시 비정상적인 동작에 대비하여 RetryTemplate 추가 (총 3번 시도, 1초 지연)
- 취향 등록 관련 로직 가독성 향상
- 
=> [#195] Fix: 취향 등록 시 동시성 문제 수정

hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/TuningResult.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/interests/service/InterestsService.java
- #199 
- 트랜잭션 충돌로 인한 낙관적 락 적용 (`@Version` 어노테이션 및 DB 내 `version` 필드 추가)
- 관심사 저장 로직에 대해 `retryTemplate` 기반 재시도 로직 추가
- `TuningResult` 엔티티 수정 도중, 동시에 여러 트랜잭션이 접근하며 낙관적 락 충돌 발생
- 예상 오류 발생 시나리오 : 한 사용자가 관심사를 저장하는 동안, 동시에 다른 트랜잭션에서 같은 튜닝 결과를 갱신
- 이를 해결하기 위해 `@Version` 필드 추가 및 DB 테이블에 `version` 컬럼 반영
- 낙관적 락 예외(`ObjectOptimisticLockingFailureException`) 발생 시 최대 3회까지 재시도하도록 `retryTemplate` 적용
- 트랜잭션 커밋 이후에 실행되는 AI 서버 호출 로직(`afterCommit`)은 기존대로 유지하며, 별도로 재시도 처리도 포함
- version 컬럼은 `BIGINT DEFAULT 0`으로 DB에 추가되어야 함
<br>
> 오류 발생 트랜잭션
> 직전 발생한 트랜잭션
=> [#199] Fix: 낙관적 락 적용 및 트랜잭션 충돌 재시도 처리

.github/workflows/cicd-backend.yml
- x
- cd 실패 시 rollback으로 넘어가지 않는 오류 수정
- cd 실패 exit 1로 종료되는 트리거를 rollback job에서 인식하지 못해 문제가 생김
- rollback job의 트리거에 `if: always() && needs.frontend-cd.result != 'success'`를 설정
- cd job에서 exit 1을 뱉고 끝내더라도, rollback job에 `always()`를 넣어 해당 job을 인식하게 설정하고, `&& needs.frontend-cd.result != 'success'` 조건을 추가로 걸어 cd job이 실패했을 때만 수행됨
=> fix: cd 실패 시 rollback으로 넘어가지 않는 오류 수정

hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/controller/ChannelController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java
- #215 
- MVP 단계에서 구현했지만, 이제는 SSE가 도입됨에 따라 더 이상 사용되지 않는 API 삭제
- ChannelController에서 해당 API의 메서드 삭제
- ChannelService에서 해당 API의 메서드 삭제
- 없음
- 없음
=> [#215] Refactor: 새 메세지 여부 API 삭제

hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/interests/service/InterestsService.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/UserController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/dto/response/InterestsDTO.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/dto/response/KeywordsDTO.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/dto/response/UserProfileDTO.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/repository/UserRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/service/UserService.java, hertz-be/src/main/java/com/hertz/hertz_be/global/common/ResponseCode.java
- #88 
- 마이페이지 정보 조회 가능
- 상대방 상세 페이지 정보 조회 가능
- 관심사 매핑 관련 기능을 공통 메서드로 처리
- 마이페이지 내 사용자의 개인정보, 취향정보 조회 가능 (keywords, interests)
- 상대방 상세 페이지 내 상대방의 개인정보, 취향정보 조회 가능 (keywords, interests, sameInterests)
- 시그널 상태 : keywords, sameInterests 까지만 공개 (프론트에서 interests는 블러처리)
- 매칭 상태 : keywords, sameInterests, interests 모두 공개
- 기존에 채널 도메인에서만 사용하던 관심사 매핑 관련 함수를 공통 메서드로 처리하여 사용자 도메인에서도 사용할 수 있도록 함
- 큰 기능은 없지만 리뷰해주실 부분이 있다면 코멘트 부탁드립니다!
- 시그널/매칭 상태에 따른 code, message 분리가 불필요한 것 같아 통일하였습니다. [API 명세서 참고](https://docs.google.com/spreadsheets/d/19OiUmoIrlbFr20BKg5lpO1wkBBeqZ8rd7ZEcPmRCkho/edit?gid=1448614724#gid=1448614724&range=A13:H16)
=> [#88] Feat: 사용자 정보 조회 기능 구현

hertz-be/src/main/java/com/hertz/hertz_be/domain/alarm/controller/AlarmController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/alarm/dto/response/AlarmListResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/alarm/dto/response/object/AlarmItem.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/alarm/dto/response/object/MatchingAlarm.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/alarm/dto/response/object/NoticeAlarm.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/alarm/dto/response/object/ReportAlarm.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/alarm/entity/AlarmMatching.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/alarm/entity/enums/AlarmCategory.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/alarm/repository/UserAlarmRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/alarm/service/AlarmService.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/SignalRoom.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/Tuning.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/enums/Category.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/enums/ChannelCategory.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/enums/MatchingStatus.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/TuningRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java, hertz-be/src/main/java/com/hertz/hertz_be/global/common/ResponseCode.java
- #244 
- 특정 사용자를 위한 최근 30일 동안 모든 알림 반환 API를 위한 로직 구현
- 사용자 조직(이메일) 별로 구분해서 적절한 알림 반환
- 페이징을 통해 한번에 10개 알림 데이터 반환
- 최근 30일 동안 발생한 알림만 반환
- 알람 종류 총 3가지: 매칭 결과, 공지, 튜닝레포트
- SignalRoom 엔티티에서 사용자 나감을 나타내는 컬럼 추가
- 없음
- 없음
=> [#244] Feat: 특정 사용자를 위한 최근 30일 동안 모든 알림 반환 API 구현

hertz-be/src/main/java/com/hertz/hertz_be/domain/alarm/repository/AlarmMatchingRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/alarm/service/AlarmService.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/AsyncChannelService.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java, hertz-be/src/main/java/com/hertz/hertz_be/global/util/MessageCreatorUtil.java
- #246 
- 기존 매칭 처리 로직에서 비동기적으로 알림 생성 기능 추가
- 매칭 처리 시 알림 생성을 비동기 방식으로 수행하도록 개선
- `AlarmService`에 매칭 알림 생성 메서드 (`createMatchingAlarmAsync`) 추가
- 문자열 기반 알림 메시지 생성을 위한 `MessageCreatorUtil` 유틸 클래스 구현
- 없음
- 없음
=> [#246] Feat: 매칭 결과 알림 생성 로직 구현

hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/OAuthController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/dto/response/OAuthLoginResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/dto/response/OAuthLoginResult.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/dto/response/OAuthSignupResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/dto/response/ReissueAccessTokenResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/object/UserMessageCountDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/SendSignalResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/TuningResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/sse/ChannelListResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/sse/MatchingConvertedInChannelRoomResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/sse/MatchingConvertedResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/sse/MatchingResultResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/sse/NewMessageResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/AsyncChannelService.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/SseChannelService.java
- #251 
- 기존 `ResponseDTO` 클래스들을 Java `record` 타입으로 리팩토링
- `@Getter`, `@AllArgsConstructor`, `@Builder` 등 보일러플레이트 애노테이션 제거
- 서비스 및 컨트롤러 내부에서 DTO 생성 방식을 `new Record(...)` 생성자 방식으로 변경
---
- 기존 `ResponseDTO` 클래스에 불필요한 코드가 많아 가독성과 유지보수성이 떨어졌습니다.
- Java 14 이상에서 지원하는 `record` 타입을 적용하여 DTO를 간결하고 명확하게 정의했습니다.
- record는 생성자, getter, toString, equals 등을 자동으로 생성하므로, DTO의 본래 목적에 부합하는 방식입니다.
- 서비스 로직, 컨트롤러 로직에서 `.builder()` 대신 `new ResponseDto(...)` 생성 방식으로 변경했습니다.
- 응답 DTO의 불변성을 보장하며, 명확한 데이터 전달 객체로 기능을 제한함으로써 안정성을 높였습니다.
---
- 없음
- 없음
=> [#251] Refactor: ResponseDTO 클래스 record 타입으로 리팩토링

hertz-be/src/main/java/com/hertz/hertz_be/domain/tuningreport/entity/TuningReport.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/tuningreport/service/TuningReportReactionService.java
- reactionCount를 해당 튜닝 리포트의 전체 개수로 잘못 보내고 있었음
- 각 reaction에 대한 개별 count로 보낼 수 있도록 수정
=> Fix: 튜닝 리포트 리액션 토글 내 리액션 개수 수정

hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/controller/ChannelController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/SignalRoom.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/enums/MatchingStatus.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/exception/AlreadyExitedChannelRoomException.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/exception/ChannelExceptionHandler.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/SignalRoomRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/projection/ChannelRoomProjection.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java, hertz-be/src/main/java/com/hertz/hertz_be/global/common/ResponseCode.java
- #87 
- 사용자가 채널방(시그널룸)을 나갈 수 있는 API 추가: `DELETE /api/v2/channel-rooms/{channelRoomId}`
- 소프트 델리트를 위한 나간 시간 기록 (`senderExitedAt`, `receiverExitedAt`)
- 중복 요청 방지를 위한 예외 처리 (`AlreadyExitedChannelRoomException`)
---
- 사용자가 매칭된 상대방과의 대화를 중단하고 싶을 경우, 채널방을 자율적으로 나갈 수 있도록 기능을 추가했습니다.
- 실제 DB 삭제는 수행하지 않고, `SignalRoom` 엔티티의 `senderExitedAt` 또는 `receiverExitedAt` 필드에 `LocalDateTime.now()`를 기록하여 소프트 델리트 형태로 처리합니다.
- 해당 정보는 추후 매칭 알고리즘에서 **재매칭 방지 조건**으로 활용될 수 있습니다.
- 사용자가 이미 나간 채널방에 대해 다시 나가기 요청을 보내는 경우, `AlreadyExitedChannelRoomException`을 통해 명확한 예외 메시지를 반환합니다.
- 클라이언트에서는 이 필드를 기준으로 채널방 목록에서 제외하거나 "나간 채팅방" 상태로 표시할 수 있습니다.
- 없음
- 없음
=> [#87] Feat: 채널방 나가기 API 구현

hertz-be/src/main/java/com/hertz/hertz_be/global/sse/SseService.java, hertz-be/src/main/resources/application-dev.properties, hertz-be/src/main/resources/application-local.properties, hertz-be/src/main/resources/application-prod.properties
- #271 
- `spring.jpa.open-in-view=false` 설정을 추가하여 JPA 트랜잭션 범위를 명시적으로 제한
- 기존 설정에서는 `spring.jpa.open-in-view=true`가 기본값으로 활성화되어 있었고,
이로 인해 **트랜잭션이 View 렌더링 혹은 SSE 응답까지 열린 채로 유지**되었습니다.
- 이 구조에서 `SseEmitter`와 함께 Lazy Loading이 발생하거나 응답 지연이 길어지면,
**커넥션이 즉시 반환되지 않고 풀을 고갈시키는 문제**가 발생했습니다.
- `application.properties`에 다음 설정을 추가하여 View 이후에는 트랜잭션이 이어지지 않도록 변경
```properties
spring.jpa.open-in-view=false
- https://techblog.woowahan.com/2664/
- https://techblog.woowahan.com/2663/
- https://haedal-uni.github.io/posts/SSE-%EB%AC%B8%EC%A0%9C%EC%A0%90/
=> [#271] Fix: HikariCP: active 커넥션 고정 상태로 커넥션 반환하지 않는 문제 해결

hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/ChannelRoomResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/entity/SignalRoom.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/ChannelService.java
- #281 
- `SignalRoom` 엔티티에 상대방이 채팅방을 나갔는지 확인하는 메서드 `isPartnerExited` 추가
- `ChannelRoomResponseDto`에 `hasPartnerExited` 필드 추가 및 `of` 팩토리 메서드에 파라미터 반영
- `ChannelService#getChannelRoom`에서 상대방의 나간 상태 여부를 조회하고 응답 DTO에 포함하도록 로직 수정
- 기존에는 채팅방 상세 조회 시 상대방이 채팅방을 나갔는지 여부를 클라이언트에서 알 수 없었음
- 이를 해결하기 위해 `SignalRoom`에 `isPartnerExited` 메서드를 구현하여 현재 사용자의 상대방 나간 상태를 쉽게 확인 가능하도록 함
- `ChannelRoomResponseDto`에 `hasPartnerExited` 필드를 추가하여 응답에 포함되도록 변경
- `getChannelRoom` 서비스 로직에서 `isPartnerExited` 결과를 조회해 DTO 생성 시 전달
- 이를 통해 프론트엔드에서 상대방이 이미 나간 채팅방임을 감지하여 채팅 입력창 비활성화 등 적절한 UI 처리가 가능함
- 없음
- 없음
=> [#281] Feat: 채팅방 반환 시 상대방이 나간 채팅방인지 여부를 나타내는 필드 추가

hertz-be/src/main/java/com/hertz/hertz_be/global/config/SocketIoConfig.java, hertz-be/src/main/java/com/hertz/hertz_be/global/infra/ai/dto/AiSignalRoomDto.java, hertz-be/src/main/java/com/hertz/hertz_be/global/socketio/SocketIoServerRunner.java
- 
- Merge Conflict 오류 해결
- dto 구조 수정
- Socket.io 쪽 바인딩 시 포트 충돌로 인해 Bean 생성에 문제 생기는 부분 수정
- dto 오타 수정
- Socket.io -> SoketIoConfig.java 내 server.start()에서 SocketIoServerRunner.java로 start/stop 분리 작업
- 포트 충돌이 나더라도 Bean 생성 단계에서 예외를 방지
- 명시적으로 서버 실행 로직을 분리함으로써 안정적으로 해결
=> Fix: merge conflict 해결 (dto 구조 변경 및 포트 바인딩 충돌 해결)

hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/OAuthController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/controller/v1/ChannelController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/controller/v2/ChannelController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/controller/v3/ChannelController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/request/v1/SendSignalRequestDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/request/v1/SignalMessageRequestDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/request/v2/SignalMatchingRequestDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/request/v3/SendSignalRequestDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/v1/ChannelListResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/v1/ChannelRoomResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/v1/ChannelSummaryDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/v1/DecryptedChannelSummaryConverter.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/v1/SendSignalResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/v1/TuningResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/v3/ChannelListResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/v3/ChannelRoomResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/v3/ChannelSummaryDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/v3/SendSignalResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/SignalRoomRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/projection/ChannelRoomProjection.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/v1/ChannelService.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/v2/ChannelService.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/v3/ChannelService.java
- #309 
- `channel` 도메인 `controller`, `dto`, `service` 클래스 버전별로 분리 (`refactor`)
- 개인 채널보관함 목록 반환 API 응답 데이터 구조 수정 (`feat`)
- 특정 채널방 반환 API 응답 데이터 구조 수정 (`feat`)
- 시그널 보내기 API 요청 데이터에 `category` 필드 추가 (`feat`)
---
- 3차 카테고리 기능 대응을 위해 **채팅방 관련 응답 데이터에 `category` 필드 추가**
- 현재 채팅 중인 상대방과의 관계 카테고리를 프론트에서 식별 가능하도록 개선
- `channel` 도메인 구조를 버전별로 세분화하여 유지보수성과 확장성 향상
- 기존 채널보관함 및 특정 채널방 조회 API에서 Projection 및 DTO에 `category` 포함되도록 쿼리 및 매핑 로직 수정
- 시그널 전송 시 `category` 정보를 함께 전달하도록 요청 DTO 확장
- 없음
- 없음
=> [#309] Feat: 시그널 보내기 & 채팅방 관련 데이터 반환시 응답데이터에 관계의 카테고리 필드 추가

hertz-be/src/main/java/com/hertz/hertz_be/domain/alarm/service/AlarmService.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/controller/AuthController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/auth/service/OAuthService.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/controller/v1/ChannelController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/controller/v2/ChannelController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/v1/ChannelService.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/v3/ChannelService.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/interests/controller/InterestsController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/v1/UserController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/v3/UserController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/dto/request/v3/RejectCategoryChangeRequestDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/entity/User.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/responsecode/UserResponseCode.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/service/v1/UserService.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/service/v2/UserService.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/service/v3/UserService.java
- #312 
- 카테고리별 시그널 수신 설정을 수정할 수 있는 RequestDto 구현
- `category` 필드가 포함된 DTO 클래스 생성
- 사용자 Entity에 설정 변경 메서드(`changeRejectCategory`) 추가
- API 응답 코드 및 예외 처리 로직 추가
- 컨트롤러에 API 메서드 추가 및 `@Valid` 어노테이션 적용
- 서비스 계층 메서드에 `@Transactional` 어노테이션 추가
- 사용자가 마이페이지에서 특정 시그널 카테고리(`COUPLE`, `FRIEND`)에 대한 수신 여부를 설정할 수 있도록 기능을 구현했습니다.
- 요청 본문에는 사용자가 off 하고자 하는 카테고리를 전달하며, 서버에서는 해당 카테고리에 대한 시그널 수신 플래그를 수정합니다.
- `ChangeSignalReceiveCategoryRequestDto` 클래스에는 `Category category`와 `Boolean isAllowed` 필드를 포함시켜 유연하게 동작할 수 있도록 구성했습니다.
- 사용자 엔티티 내부에서 `changeRejectCategory` 메서드를 통해 요청된 카테고리에 따라 `isFriendAllowed` 또는 `isCoupleAllowed` 값을 수정합니다.
- 컨트롤러에서 해당 API를 `@Valid`와 함께 매핑하고, 서비스 계층에서는 트랜잭션 처리를 통해 안정적인 데이터 갱신을 보장합니다.
- 향후 `Category`가 추가될 경우를 대비해 `switch` 문으로 명시적 분기 처리하도록 설계했습니다.
- 없음
- 없음
=> [#312] Feat: 시그널을 받고 싶지 않은 카테고리 수정 API 구현

hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/controller/v3/ChannelController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/response/v3/TuningResponseDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/SignalRoomRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/TuningRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/TuningResultRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/v3/ChannelService.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/interests/service/InterestsService.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/entity/User.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/responsecode/UserResponseCode.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/service/v3/UserService.java, hertz-be/src/main/java/com/hertz/hertz_be/global/config/WebClientConfig.java, hertz-be/src/main/java/com/hertz/hertz_be/global/infra/ai/client/TuningAiClient.java, hertz-be/src/main/resources/application-dev.properties
- #316 
- 카테고리(친구/커플)별 튜닝 추천 API 구현
- 사용자별 카테고리 설정 여부에 따른 추천 필터링 로직 추가
- AI 서버와의 연동을 통한 추천 결과 수신 기능 추가
- 이미 대화 중이거나, 시그널 차단 설정된 경우 예외 처리 추가
- 기존에는 친구 관계를 전제로 튜닝 추천이 이뤄졌으나, 커플 등 다른 관계 목적의 추천 니즈를 반영하기 위해 카테고리 구분이 필요해졌습니다.
- 이에 따라 V3 채널 도메인 내에서 **카테고리별 튜닝 추천 API**를 새로 정의하고, 기본 카테고리(친구) 외에도 커플 등으로 확장 가능하도록 구조를 개선했습니다.
- 구현 주요 내용:
- **AI 서버 API 연동**: WebClient를 이용해 카테고리별 추천 요청 전송 및 응답 처리
- **ResponseDto 구현**: 카테고리별 추천 결과를 담을 DTO 생성
- **Service / Controller 추가**: 카테고리 인자를 기반으로 AI 서버 추천 요청 및 사용자 필터링 처리
- **사용자 카테고리 허용 여부 확인**: user entity에 특정 카테고리가 허용되는지 반환하는 메서드 구현
- **추천 리스트 필터링 로직**: 추천 받은 사용자 리스트 중에서 해당 카테고리를 false로 설정한 사용자를 제외하는 로직 추가
- **추천 리스트 업데이트 로직**: 사용자가 특정 카테고리를 false로 설정할 시, 해당 사용자가 포함된 모든 추천 리스트에서 제외하는 로직 추가
- **예외 처리**: 
- 이미 해당 카테고리로 대화 중인 상대방이 존재하면 예외 발생
- 시그널 전송 시 해당 카테고리를 …
=> [#316] Feat: 카테고리별 튜닝 추천 API 구현 및 AI 서버 API 연동

hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/controller/v1/ChannelController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/dto/request/v3/SendMessageRequestDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/v1/ChannelService.java, hertz-be/src/main/java/com/hertz/hertz_be/global/config/SocketIoConfig.java, hertz-be/src/main/java/com/hertz/hertz_be/global/socketio/SocketIoService.java
- 
- 시그널 보내기 / 메세지 전송 DTO 분리
- `markMessageAsRead` 메서드의 `@Transactional` 설정 변경
- '시그널 보내기' 기능과 '메세지 전송'의 요청 구조가 다름에도 불구하고 함께 사용하고 있는 부분이 있어 DTO를 분리함
- Socket.io는 Spring MVC의 DispatcherServlet이나 AOP 기반의 트랜잭션 관리와는 무관한 별도의 Netty 기반 I/O 이벤트 루프에서 작동하게 됨, 따라서 @Transactional이 정상적으로 동작하지 않거나, 커넥션이 read-only로 설정될 수 있음
- @Transactional 에 대한 추가 설정
- readOnly = false -> 상위에서 걸린 readOnly = true 설정 무시
- propagation = Propagation.REQUIRES_NEW -> 독립적인 트랜잭션으로 돌아갈 수 있도록 명시
- 트랜잭션 전파 차단 설정을 함으로써 새로운 트랜잭션을 열어 DB 수정이 가능하도록 보장함
=> Fix: socket.io 메세지 읽음 처리 관련 트랜잭션 설정 변경

hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/v3/UserController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/dto/request/v3/OneLineIntroductionRequestDto.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/entity/User.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/responsecode/UserResponseCode.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/service/v3/UserService.java
- #325 
- 마이페이지 내 한 줄 소개를 수정할 수 있도록 기능 구현
- `/api/v3/users` -> `/api/v3/users/{userId}`으로 API 명세 수정
- 기존 url은 `JwtAuthenticationFilter`에서 `EXCLUDE_PATHS`로 관리되고 있었음
- 마이페이지 관련해서는 뒤에 `PathVariable`로 관리하고 있었기 때문에 `{userId}`를 붙이는 것이 맞다고 판단
- [API 명세서](https://docs.google.com/spreadsheets/d/19OiUmoIrlbFr20BKg5lpO1wkBBeqZ8rd7ZEcPmRCkho/edit?gid=461270540#gid=461270540) - `개인정보 수정 페이지 > 한줄 소개 수정` 참고
=> [#325] Feat: 마이페이지 한 줄 소개 수정 API 구현

hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/repository/SignalMessageRepository.java, hertz-be/src/main/resources/application-dev.properties
- socket.io 메세지 읽음 처리 관련 트랜잭션 오류 처리
- repository 쿼리에 `@Modifying(clearAutomatically = true)` 설정 추가
- JPA 캐시(영속성 컨텍스트)에 남아 있는 이전 엔티티 상태와 충돌 날 수 있기 때문
=> Fix: socket.io 메세지 읽음 처리 관련 트랜잭션 오류 처리

hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/v1/ChannelService.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/v3/ChannelService.java
- ChannelService > getChannelRoom 메서드 내 @Transactional 의 readOnly = true 값을 제거
- getChannelRoom 메서드 내 쓰기 작업이 이뤄지고 있는데, @Transactional 어노테이션에 readOnly = true 옵션이 붙어있어 오류가 발생하고 있었음
```
2025-07-01 01:20:24.554 | [DB 에러] JDBC exception executing SQL [update signal_message sm1_0 set is_read=1 where sm1_0.signal_room_id=?] [Connection is read-only. Queries leading to data modification are not allowed] [n/a]
2025-07-01 01:20:24.552 | Completing transaction for [com.hertz.hertz_be.domain.channel.service.v1.ChannelService.getChannelRoom] after exception: org.springframework.orm.jpa.JpaSystemException: JDBC exception executing SQL [update signal_message sm1_0 set is_read=1 where sm1_0.signal_room_id=?] [Connection is read-only. Queries leading to data modification are not allowed] [n/a]
2025-07-01 …
```
=> Fix: Transactional의 readOnly = true 값 제거

hertz-be/src/main/java/com/hertz/hertz_be/domain/channel/service/v3/ChannelService.java, hertz-be/src/main/java/com/hertz/hertz_be/global/socketio/SocketIoController.java, hertz-be/src/main/java/com/hertz/hertz_be/global/socketio/SocketIoServerRunner.java, hertz-be/src/main/java/com/hertz/hertz_be/global/socketio/SocketIoService.java, hertz-be/src/main/java/com/hertz/hertz_be/global/socketio/dto/SocketIoMessageMarkResponse.java
- socket.io 메세지 읽음 처리 관련 트랜잭션 처리
- socket.io 서버 구동 시 예외 처리 작업 추가
- Transaction 관련 처리
- 비동기로 동작하는 웹소켓과 트랜잭션이 겹치지 않도록 알림 관련 로직에 대해 afterCommit 처리하여 커밋 완료 후 실행될 수 있게 수정
- write 작업이 들어가지 않은 메서드에 readOnly = true로 하여 트랜잭션 접근 최소화
- socket 서버 구동 시 이미 실행 중일 경우, 또 구동시키지 않도록 예외 처리
=> Fix: socket.io 메세지 읽음 처리 관련 트랜잭션 내 afterCommit 처리, socket 서버 구동 예외 처리

hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/v2/UserController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/controller/v3/UserController.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/dto/response/v3/InterestsDTO.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/dto/response/v3/KeywordsDTO.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/dto/response/v3/UserProfileDTO.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/user/service/v3/UserService.java
- #324 
- v2 -> v3 카테고리 도입으로 인한 마이페이지 조회 필드 수정
- 마이페이지에서는 본인의 freindAllowed, coupleAllowed 값 조회
- 상대방 상세 정보 페이지 조회에서는 두 필드 모두 null로 반환
=> [#324] Feat: 특정 사용자의 개인정보 및 취향반환 v3 API 구현

hertz-be/src/main/java/com/hertz/hertz_be/domain/tuningreport/repository/TuningReportRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/tuningreport/service/TuningReportReactionService.java
- TuningReportRepository에 PESSIMISTIC_WRITE 락 메서드(findWithLockById) 추가
- TuningReportReactionService에서 해당 메서드 사용하여 교착 상태 방지
- @Retryable에 Deadlock 및 Lock 관련 예외(CannotAcquireLockException 등) 추가
- 리액션 수치 업데이트 및 리액션 row 조작 순서를 트랜잭션 내에서 명확히 분리
- 잘못된 Param import (lettuce) 제거 및 Spring Data JPA용으로 정리
=> Hotfix: 튜닝 리포트 리액션 토글 시 발생하던 Deadlock 및 LockTimeout 해결

hertz-be/src/main/java/com/hertz/hertz_be/global/webpush/FCMInitializer.java
- FCM Initializer 시 오류가 발생하여 채팅방에 접근을 하지 못하는 현상 발생
- FCMInitializer라는 Bean 생성 과정에서 `@PostConstruct` 또는 InitializingBean의 `afterPropertiesSet()` 같은 초기화 메서드에서 예외가 터져서 애플리케이션이 실행되지 못한 것으로 추정
- FirebaseApp이 중복 생성되는지 의심
- 이전 테스트나 실행에서 FirebaseApp이 이미 초기화됐는데 다시 초기화하려고 할 경우 에러가 발생함
> 기존
```
if (FirebaseApp.getApps().isEmpty()) {
FirebaseApp.initializeApp(options);
log.info("FirebaseApp initialization complete");
}
```
> 변경
```
if (FirebaseApp.getApps().stream().noneMatch(app -> app.getName().equals(FirebaseApp.DEFAULT_APP_NAME))) {
FirebaseApp.initializeApp(options);
log.info("🔥 FirebaseApp initialization SUCCESS");
}
```
- 추가로 try-catch 활용하여 자세한 로그 추적 추가
=> Fix: FCM Initializer 시 예외 코드 처리

hertz-be/src/main/java/com/hertz/hertz_be/domain/alarm/dto/response/object/AlarmItem.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/alarm/entity/AlarmMatching.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/alarm/repository/UserAlarmRepository.java, hertz-be/src/main/java/com/hertz/hertz_be/domain/alarm/service/AlarmService.java, hertz-be/src/main/resources/application-local.properties
- #378 
- `AlarmMatching.signalRoom`에 대한 N+1 문제 해결을 위해 JPQL에 `JOIN FETCH` 구문 추가
- `findRecentUserAlarms` → `findRecentUserAlarmsWithSignalRoom`으로 메서드 리네이밍 및 쿼리 최적화
---
- 기존에는 `UserAlarm` 목록 조회 시, 각 알람이 `AlarmMatching` 타입일 경우 `signalRoom` 조회 시점마다 개별 쿼리가 실행되어 N+1 문제가 발생했습니다.
- 알림 10개 중 10개가 `AlarmMatching`인 경우 → 최대 12개의 SQL 실행
- 실제 응답 시간도 약 316ms 수준으로 확인됨
- 이를 해결하기 위해 `JOIN FETCH TREAT(a AS AlarmMatching).signalRoom` 구문을 JPQL에 적용하여 한 번의 SQL로 모든 필요한 데이터를 조회하도록 수정했습니다.
```java
@Query("""
SELECT ua
FROM UserAlarm ua
JOIN FETCH ua.alarm a
LEFT JOIN FETCH TREAT(a AS AlarmMatching).signalRoom sr
WHERE ua.user.id = :userId
AND a.createdAt >= :thresholdDate
ORDER BY a.createdAt DESC
""")
Page<UserAlarm> findRecentUserAlarmsWithSignalRoom(...);
```
- 쿼리 실행 횟수: 12 → 2회 (메인 조회 + COUNT)
- 응답 속도: 316ms …
=> [#378] Fix: Alarm 도메인의 Get 요청에서 발생했 N+1 문제 해결

hertz-be/src/main/java/com/hertz/hertz_be/global/config/SecurityConfig.java, hertz-be/src/main/java/com/hertz/hertz_be/global/webpush/token/FCMTokenDao.java
- Redis 내 Token에 대해 key 값을 불러올 때에 소스가 누락되어 올바르지 않은 key를 부르고 있는 이슈
- key 값을 동일하게 불러올 수 있도록 조치함
=> Fix: WebPush Redis 내 저장된 key 값 관련 소스 누락 조치
